### ISSUE TITLE
无法复现结果

### ISSUE THREAD

**Issue by everks** [chenllliang/DnD-Transformer#2]
用开源的tokenizer ckpt，使用提供的code抽取流程和AR模型训练脚本训练ImageNet 256x256 300epoch后，评测指标如下：

Inception Score: 219.31997680664062
FID: 4.574550080130052
sFID: 10.650144511617668
Precision: 0.76626
Recall: 0.5826

与论文汇报指标 fid=2.58有很大差距，请问目前提供的训练脚本与论文中模型训练有什么不同吗（比如有无lr decay）？感谢。

**Comment by chenllliang** [comment]
你好 感谢关注。训练脚本的区别是我们用了一个较大的 global-batch-size=512～1024，如果batch-size较小会出现训练不稳定的情况，可以尝试更多的训练步数例如600epochs观察fid是否继续下降，如果GPU有限可以尝试一下添加梯度累计的技巧来增加 batchsize和原始方案对齐。
